import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import "./globals.scss";
import Footer from "@/components/Footer/Footer";
import { Locale } from "@/types/museumTypes";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  return (
    <>
      <html lang={locale}>
        <body className={inter.className}>
          <StoreProvider>
            <Header locale={locale} />
            {children}
            <Footer />
          </StoreProvider>
        </body>
      </html>
    </>
  );
}
