import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Header } from "@/componets/Header";
import Footer from "@/componets/Footer/Footer";
import { i18nConfig } from "@/i18nConfig";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return i18nConfig.locales.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang={locale}>
        <body className={inter.className}>
          <Header locale={locale} />
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
